#include "grid_rot/core.hpp"
#include <cmath>
#include <iostream>
#include <vector>
using namespace grid_rot;
int main(){constexpr int w=96,h=54,frames=17;std::vector<std::vector<float>>images(frames,std::vector<float>(w*h*4));for(int f=0;f<frames;++f)for(int y=0;y<h;++y)for(int x=0;x<w;++x){auto i=(size_t(y)*w+x)*4;images[f][i]=float((x+f*3)%w)/w;images[f][i+1]=float(y)/h;images[f][i+2]=((x/8+f/2)&1)?.85f:.12f;images[f][i+3]=1;}std::vector<float>a(w*h*4),b(w*h*4),gpu(w*h*4);RenderRequest r;r.values=defaultParameters();r.mode=4;r.time_seconds=2;r.frame_number=60;r.source={images[0].data(),w,h,4,w*16};r.history_count=frames;for(int i=0;i<frames;++i)r.history[i]={images[i].data(),w,h,4,w*16};r.output={a.data(),w,h,w*16};r.values[size_t(ParameterId::DropCount)]=16;r.values[size_t(ParameterId::DropLife)]=3;r.values[size_t(ParameterId::DropSpread)]=0;r.values[size_t(ParameterId::DropSeed)]=4;r.values[size_t(ParameterId::TemporalEnabled)]=1;r.values[size_t(ParameterId::TemporalDelay)]=1;r.values[size_t(ParameterId::OpDelayEnabled)]=1;r.values[size_t(ParameterId::OpDelayWeight)]=100;r.values[size_t(ParameterId::OpDelayFrames)]=16;if(requiredPastFrames(r.values)!=16)return 1;r.values[size_t(ParameterId::OpDelayEnabled)]=0;r.values[size_t(ParameterId::OpReverseEnabled)]=1;r.values[size_t(ParameterId::OpReverseWeight)]=100;r.values[size_t(ParameterId::OpReverseFrames)]=12;if(requiredPastFrames(r.values)!=23)return 10;r.values[size_t(ParameterId::OpReverseEnabled)]=0;r.values[size_t(ParameterId::OpDelayEnabled)]=1;if(renderCpu(r)!=RenderStatus::Ok)return 2;r.output={b.data(),w,h,w*16};if(renderCpu(r)!=RenderStatus::Ok)return 3;double repeat=0,temporal=0;for(size_t i=0;i<a.size();++i){if(!std::isfinite(a[i]))return 4;repeat+=std::abs(a[i]-b[i]);temporal+=std::abs(a[i]-images[0][i]);}if(repeat>1e-7||temporal/a.size()<1e-4)return 5;r.values[size_t(ParameterId::Amount)]=0;r.output={b.data(),w,h,w*16};if(renderCpu(r)!=RenderStatus::Ok)return 6;for(size_t i=0;i<b.size();++i)if(std::abs(b[i]-images[0][i])>1e-6)return 7;
#ifdef GRID_ROT_WITH_CUDA
r.values[size_t(ParameterId::Amount)]=1;r.output={gpu.data(),w,h,w*16};if(cudaAvailable()){if(renderCuda(r)!=RenderStatus::Ok)return 8;double error=0;for(size_t i=0;i<gpu.size();++i)error+=std::abs(gpu[i]-a[i]);if(error/gpu.size()>.025)return 9;}
#endif
std::cout<<"GRID ROT deterministic CPU/CUDA temporal smoke OK\n";}