#include <algorithm>
#include <cmath>
#include <cstring>
#include <new>
#include <string>
#include <utility>
#include "ofxImageEffect.h"
#include "ofxMultiThread.h"
#include "raster_rupture/core.hpp"
using namespace raster_rupture;
static OfxHost*host=nullptr;static const OfxImageEffectSuiteV1*fx=nullptr;static const OfxPropertySuiteV1*prop=nullptr;static const OfxParameterSuiteV1*param=nullptr;static const OfxMultiThreadSuiteV1*mt=nullptr;
static constexpr size_t N=static_cast<size_t>(ParameterId::Count);
struct Instance{OfxImageEffectHandle effect;OfxImageClipHandle source,output,mask;OfxParamSetHandle set;OfxParamHandle values[N],routes[9][2],preset,style,ink,accent,channel,invert,sourceMask,useCuda;bool applying=false;};
static void check(OfxStatus s){if(s!=kOfxStatOK)throw s;} static void text(OfxPropertySetHandle p,const char*n,const char*v,int i=0){check(prop->propSetString(p,n,i,v));}static void integer(OfxPropertySetHandle p,const char*n,int v,int i=0){check(prop->propSetInt(p,n,i,v));}static void real(OfxPropertySetHandle p,const char*n,double v,int i=0){check(prop->propSetDouble(p,n,i,v));}
static OfxPropertySetHandle def(OfxParamSetHandle s,const char*t,const char*i,const char*l){OfxPropertySetHandle p;check(param->paramDefine(s,t,i,&p));text(p,kOfxPropLabel,l);return p;}static Instance*data(OfxImageEffectHandle e){OfxPropertySetHandle p;void*v=nullptr;check(fx->getPropertySet(e,&p));check(prop->propGetPointer(p,kOfxPropInstanceData,0,&v));if(!v)throw kOfxStatErrBadHandle;return static_cast<Instance*>(v);}
static OfxStatus describe(OfxImageEffectHandle e){OfxPropertySetHandle p;check(fx->getPropertySet(e,&p));text(p,kOfxPropLabel,"RASTER RUPTURE");text(p,kOfxImageEffectPluginPropGrouping,"SIGNAL CULT");text(p,kOfxImageEffectPropSupportedContexts,kOfxImageEffectContextFilter,0);text(p,kOfxImageEffectPropSupportedContexts,kOfxImageEffectContextGeneral,1);text(p,kOfxImageEffectPropSupportedPixelDepths,kOfxBitDepthFloat);text(p,kOfxImageEffectPluginRenderThreadSafety,kOfxImageEffectRenderFullySafe);integer(p,kOfxImageEffectPropSupportsTiles,0);integer(p,kOfxImageEffectPropSupportsMultiResolution,0);integer(p,kOfxImageEffectPropTemporalClipAccess,1);integer(p,kOfxImageEffectPluginPropHostFrameThreading,1);return kOfxStatOK;}
static void range(OfxPropertySetHandle p,const ParameterDescriptor&d){if(d.step==1){integer(p,kOfxParamPropDefault,int(d.initial));integer(p,kOfxParamPropMin,int(d.minimum));integer(p,kOfxParamPropMax,int(d.maximum));integer(p,kOfxParamPropDisplayMin,int(d.minimum));integer(p,kOfxParamPropDisplayMax,int(d.maximum));}else{real(p,kOfxParamPropDefault,d.initial);real(p,kOfxParamPropMin,d.minimum);real(p,kOfxParamPropMax,d.maximum);real(p,kOfxParamPropDisplayMin,d.minimum);real(p,kOfxParamPropDisplayMax,d.maximum);real(p,kOfxParamPropIncrement,d.step);integer(p,kOfxParamPropDigits,3);}}
static OfxStatus context(OfxImageEffectHandle e){OfxPropertySetHandle p;for(const char*n:{"Source","Output"}){check(fx->clipDefine(e,n,&p));text(p,kOfxImageEffectPropSupportedComponents,kOfxImageComponentRGBA);integer(p,kOfxImageEffectPropSupportsTiles,0);}check(fx->clipDefine(e,"Mask",&p));text(p,kOfxImageEffectPropSupportedComponents,kOfxImageComponentRGBA,0);text(p,kOfxImageEffectPropSupportedComponents,kOfxImageComponentAlpha,1);integer(p,kOfxImageClipPropOptional,1);integer(p,kOfxImageEffectPropSupportsTiles,0);OfxParamSetHandle s;check(fx->getParamSet(e,&s));auto page=def(s,kOfxParamTypePage,"controlsPage","Controls");int pi=0;for(const char*n:{"preset","look","masking","routing","rupture","surface","memory","signal","output"})text(page,kOfxParamPropPageChild,n,pi++);
 p=def(s,kOfxParamTypeChoice,"preset","Factory Preset");text(p,kOfxParamPropChoiceOption,"Custom",0);for(size_t i=0;i<kFactoryPresets.size();i++)text(p,kOfxParamPropChoiceOption,kFactoryPresets[i].name,int(i+1));integer(p,kOfxParamPropDefault,1);integer(p,kOfxParamPropAnimates,0);
 p=def(s,kOfxParamTypeGroup,"look","Look");integer(p,kOfxParamPropGroupOpen,1);auto style=def(s,kOfxParamTypeChoice,"style","Print / Glitch Style");text(style,kOfxParamPropParent,"look");int option=0;for(const char*n:{"Transmission","Xerox","Dry Ink","Thermal","Motion"})text(style,kOfxParamPropChoiceOption,n,option++);integer(style,kOfxParamPropDefault,0);for(auto entry:{std::pair{"ink","Ink Color"},std::pair{"accent","Accent Color"}}){auto c=def(s,kOfxParamTypeRGB,entry.first,entry.second);text(c,kOfxParamPropParent,"look");auto col=!std::strcmp(entry.first,"ink")?std::array<double,3>{.91,.89,.85}:std::array<double,3>{1,.15,.22};for(int i=0;i<3;i++)real(c,kOfxParamPropDefault,col[i],i);}
 p=def(s,kOfxParamTypeGroup,"masking","Mask Input");integer(p,kOfxParamPropGroupOpen,1);auto b=def(s,kOfxParamTypeBoolean,"sourceAsMask","Source as Mask");text(b,kOfxParamPropParent,"masking");integer(b,kOfxParamPropDefault,0);auto ch=def(s,kOfxParamTypeChoice,"maskChannel","Mask Channel");text(ch,kOfxParamPropParent,"masking");option=0;for(const char*n:{"Luminance","Red","Green","Blue","Alpha"})text(ch,kOfxParamPropChoiceOption,n,option++);auto inv=def(s,kOfxParamTypeBoolean,"invertMask","Invert Mask");text(inv,kOfxParamPropParent,"masking");auto gpu=def(s,kOfxParamTypeBoolean,"useCuda","Use CUDA when available");text(gpu,kOfxParamPropParent,"masking");integer(gpu,kOfxParamPropDefault,1);integer(gpu,kOfxParamPropAnimates,0);
 p=def(s,kOfxParamTypeGroup,"routing","Mask Routing");integer(p,kOfxParamPropGroupOpen,0);for(int i=0;i<9;i++){for(int a=0;a<2;a++){std::string id=std::string("route_")+kRouteIds[i]+(a?"_angle":"_influence"),label=std::string(kRouteLabels[i])+(a?" — Angle":" — Influence");auto r=def(s,kOfxParamTypeDouble,id.c_str(),label.c_str());text(r,kOfxParamPropParent,"routing");real(r,kOfxParamPropDefault,(i==5||i==6)&&!a?-1:(a?0:1));real(r,kOfxParamPropMin,a?-90:-1);real(r,kOfxParamPropMax,a?90:1);real(r,kOfxParamPropDisplayMin,a?-90:-1);real(r,kOfxParamPropDisplayMax,a?90:1);real(r,kOfxParamPropIncrement,a?1:.01);}}
 const char*groupIds[]={"rupture","surface","memory","signal","output"};const char*groupNames[]={"Rupture","Surface / Print","Memory / Xerox","Accent Signal","Output"};for(int i=0;i<5;i++){p=def(s,kOfxParamTypeGroup,groupIds[i],groupNames[i]);integer(p,kOfxParamPropGroupOpen,i<2);}for(const auto&d:kParameterDescriptors){auto v=def(s,d.step==1?kOfxParamTypeInteger:kOfxParamTypeDouble,d.id,d.label);auto id=std::string(d.id);const char*g=id.find("surface")!=std::string::npos||id.find("fiber")!=std::string::npos||id.find("Detail")!=std::string::npos||id.find("threshold")!=std::string::npos||id.find("Grain")!=std::string::npos||id.find("erosion")!=std::string::npos?"surface":id.find("feedback")!=std::string::npos||id.find("echo")!=std::string::npos||id.find("xerox")!=std::string::npos||id.find("Generations")!=std::string::npos?"memory":id.find("accent")!=std::string::npos||id.find("bloom")!=std::string::npos?"signal":id=="amount"?"output":"rupture";text(v,kOfxParamPropParent,g);range(v,d);}return kOfxStatOK;}
static OfxStatus create(OfxImageEffectHandle e){auto d=new Instance{};try{d->effect=e;check(fx->clipGetHandle(e,"Source",&d->source,nullptr));check(fx->clipGetHandle(e,"Output",&d->output,nullptr));check(fx->clipGetHandle(e,"Mask",&d->mask,nullptr));check(fx->getParamSet(e,&d->set));for(size_t i=0;i<N;i++)check(param->paramGetHandle(d->set,kParameterDescriptors[i].id,&d->values[i],nullptr));for(int i=0;i<9;i++)for(int a=0;a<2;a++){std::string id=std::string("route_")+kRouteIds[i]+(a?"_angle":"_influence");check(param->paramGetHandle(d->set,id.c_str(),&d->routes[i][a],nullptr));}for(auto x:{std::pair{"preset",&d->preset},std::pair{"style",&d->style},std::pair{"ink",&d->ink},std::pair{"accent",&d->accent},std::pair{"maskChannel",&d->channel},std::pair{"invertMask",&d->invert},std::pair{"sourceAsMask",&d->sourceMask},std::pair{"useCuda",&d->useCuda}})check(param->paramGetHandle(d->set,x.first,x.second,nullptr));OfxPropertySetHandle p;check(fx->getPropertySet(e,&p));check(prop->propSetPointer(p,kOfxPropInstanceData,0,d));return kOfxStatOK;}catch(...){delete d;throw;}}
static OfxStatus changed(OfxImageEffectHandle e,OfxPropertySetHandle in){auto d=data(e);char*n=nullptr,*reason=nullptr;prop->propGetString(in,kOfxPropName,0,&n);prop->propGetString(in,kOfxPropChangeReason,0,&reason);if(!n||!reason||std::strcmp(reason,kOfxChangeUserEdited)||d->applying)return kOfxStatReplyDefault;if(!std::strcmp(n,"preset")){int index=0;param->paramGetValue(d->preset,&index);if(index<1||index>int(kFactoryPresets.size()))return kOfxStatOK;auto&p=kFactoryPresets[index-1];d->applying=true;param->paramEditBegin(d->set,"Apply Raster Rupture preset");param->paramSetValue(d->style,p.style);param->paramSetValue(d->ink,double(p.ink[0]),double(p.ink[1]),double(p.ink[2]));param->paramSetValue(d->accent,double(p.accent[0]),double(p.accent[1]),double(p.accent[2]));for(size_t i=0;i<N;i++)kParameterDescriptors[i].step==1?param->paramSetValue(d->values[i],int(p.values[i])):param->paramSetValue(d->values[i],double(p.values[i]));for(int i=0;i<9;i++)for(int a=0;a<2;a++)param->paramSetValue(d->routes[i][a],double(p.routes[i][a]));param->paramEditEnd(d->set);d->applying=false;return kOfxStatOK;}param->paramSetValue(d->preset,0);return kOfxStatReplyDefault;}
struct Image{OfxPropertySetHandle h=nullptr;~Image(){if(h)fx->clipReleaseImage(h);}};static ConstImageView readImage(OfxPropertySetHandle h){void*p=nullptr;int b[4],rb=0;char*depth=nullptr,*components=nullptr;check(prop->propGetPointer(h,kOfxImagePropData,0,&p));check(prop->propGetIntN(h,kOfxImagePropBounds,4,b));check(prop->propGetInt(h,kOfxImagePropRowBytes,0,&rb));check(prop->propGetString(h,kOfxImageEffectPropPixelDepth,0,&depth));check(prop->propGetString(h,kOfxImageEffectPropComponents,0,&components));if(!p||std::strcmp(depth,kOfxBitDepthFloat))throw kOfxStatErrFormat;int c=!std::strcmp(components,kOfxImageComponentAlpha)?1:!std::strcmp(components,kOfxImageComponentRGBA)?4:0;if(!c)throw kOfxStatErrFormat;return{static_cast<float*>(p),b[2]-b[0],b[3]-b[1],c,rb};}
static OfxStatus render(OfxImageEffectHandle e,OfxPropertySetHandle in){auto d=data(e);double time=0;check(prop->propGetDouble(in,kOfxPropTime,0,&time));Image src,dst,mask,previous;check(fx->clipGetImage(d->source,time,nullptr,&src.h));check(fx->clipGetImage(d->output,time,nullptr,&dst.h));fx->clipGetImage(d->mask,time,nullptr,&mask.h);fx->clipGetImage(d->source,time-1,nullptr,&previous.h);RenderRequest r;r.source=readImage(src.h);auto o=readImage(dst.h);r.output={const_cast<float*>(o.data),o.width,o.height,o.row_bytes};if(mask.h)r.mask=readImage(mask.h);if(previous.h)r.previous=readImage(previous.h);r.look=defaultLook();for(size_t i=0;i<N;i++){double v;kParameterDescriptors[i].step==1?([&]{int n=0;check(param->paramGetValueAtTime(d->values[i],time,&n));v=n;}()):check(param->paramGetValueAtTime(d->values[i],time,&v));r.look.parameters[i]=std::clamp(v,double(kParameterDescriptors[i].minimum),double(kParameterDescriptors[i].maximum));}int iv=0;param->paramGetValueAtTime(d->style,time,&iv);r.look.style=iv;param->paramGetValueAtTime(d->channel,time,&r.look.mask_channel);param->paramGetValueAtTime(d->invert,time,&iv);r.look.invert_mask=iv;param->paramGetValueAtTime(d->sourceMask,time,&iv);r.look.source_as_mask=iv;double a,b,c;param->paramGetValueAtTime(d->ink,time,&a,&b,&c);r.look.ink={float(a),float(b),float(c)};param->paramGetValueAtTime(d->accent,time,&a,&b,&c);r.look.accent={float(a),float(b),float(c)};for(int i=0;i<9;i++)for(int q=0;q<2;q++){double v;param->paramGetValueAtTime(d->routes[i][q],time,&v);r.look.routes[i][q]=float(v);}OfxPropertySetHandle cp;double fps=24;if(fx->clipGetPropertySet(d->source,&cp)==kOfxStatOK)prop->propGetDouble(cp,kOfxImageEffectPropFrameRate,0,&fps);r.time_seconds=time/(fps>0?fps:24);param->paramGetValue(d->useCuda,&iv);auto status=iv&&cudaAvailable()?renderCuda(r):renderCpu(r);return status==RenderStatus::Ok?kOfxStatOK:kOfxStatFailed;}
static OfxStatus entry(const char*action,const void*handle,OfxPropertySetHandle in,OfxPropertySetHandle out){try{auto e=(OfxImageEffectHandle)handle;if(!std::strcmp(action,kOfxActionLoad)){fx=(const OfxImageEffectSuiteV1*)host->fetchSuite(host->host,kOfxImageEffectSuite,1);prop=(const OfxPropertySuiteV1*)host->fetchSuite(host->host,kOfxPropertySuite,1);param=(const OfxParameterSuiteV1*)host->fetchSuite(host->host,kOfxParameterSuite,1);mt=(const OfxMultiThreadSuiteV1*)host->fetchSuite(host->host,kOfxMultiThreadSuite,1);return fx&&prop&&param?kOfxStatOK:kOfxStatErrMissingHostFeature;}if(!std::strcmp(action,kOfxActionUnload))return kOfxStatOK;if(!std::strcmp(action,kOfxActionDescribe))return describe(e);if(!std::strcmp(action,kOfxImageEffectActionDescribeInContext))return context(e);if(!std::strcmp(action,kOfxActionCreateInstance))return create(e);if(!std::strcmp(action,kOfxActionDestroyInstance)){delete data(e);return kOfxStatOK;}if(!std::strcmp(action,kOfxActionInstanceChanged))return changed(e,in);if(!std::strcmp(action,kOfxImageEffectActionRender))return render(e,in);if(!std::strcmp(action,kOfxImageEffectActionGetFramesNeeded)){double time=0;check(prop->propGetDouble(in,kOfxPropTime,0,&time));double frames[]={time-1,time};check(prop->propSetDoubleN(out,"OfxImageClipPropFrameRange_Source",2,frames));return kOfxStatOK;}if(!std::strcmp(action,kOfxImageEffectActionGetClipPreferences)){text(out,"OfxImageClipPropComponents_Output",kOfxImageComponentRGBA);text(out,"OfxImageClipPropDepth_Output",kOfxBitDepthFloat);integer(out,kOfxImageEffectFrameVarying,1);return kOfxStatOK;}return kOfxStatReplyDefault;}catch(OfxStatus s){return s;}catch(const std::bad_alloc&){return kOfxStatErrMemory;}catch(...){return kOfxStatFailed;}}
static void setHost(OfxHost*h){host=h;}static OfxPlugin plugin={kOfxImageEffectPluginApi,1,"com.signalcult.rasterrupture",1,0,setHost,entry};extern "C"{OfxExport int OfxGetNumberOfPlugins(){return 1;}OfxExport OfxPlugin*OfxGetPlugin(int i){return i==0?&plugin:nullptr;}}
