export const destinations=[
 {key:'global',label:'Global effect'},
 {key:'tear',label:'Tear generation'},
 {key:'displacement',label:'Displacement'},
 {key:'smear',label:'Smear source'},
 {key:'feedbackWrite',label:'Feedback write'},
 {key:'feedbackRead',label:'Feedback read'},
 {key:'surface',label:'Surface damage'},
 {key:'accent',label:'Accent color'},
 {key:'flow',label:'Optical flow'}
];
export const maskSources=['MASK'];
export const fields=[
 {key:'tearAmount',label:'Tear amount',min:0,max:1,step:.01,value:.68,hint:'Probability and directional reach of signal tears.'},
 {key:'bandScale',label:'Band density',min:8,max:220,step:1,value:96,hint:'Number of independently damaged bands across the selected direction.'},
 {key:'tearComplexity',label:'Tear complexity',min:0,max:1,step:.01,value:.76,hint:'Layer fine, medium and broad ruptures instead of one uniform band scale.'},
 {key:'directionAngle',label:'Rupture direction',min:-180,max:180,step:1,value:0,hint:'Rotate bands, smears, echoes, fibers, feedback and signals; 90 degrees is vertical.'},
 {key:'crossAmount',label:'Cross rupture',min:0,max:1,step:.01,value:0,hint:'Add a secondary perpendicular displacement and smear system.'},
 {key:'smearLength',label:'Smear length',min:0,max:.5,step:.005,value:.19,hint:'Distance that selected source pixels drag across the raster.'},
 {key:'waveAmount',label:'Wave distortion',min:0,max:.08,step:.001,value:.018,hint:'Fine analogue displacement inside active tear bands.'},
 {key:'feedback',label:'Feedback persistence',min:0,max:.995,step:.005,value:.91,hint:'Retention of previous ruptured frames.'},
 {key:'feedbackDrift',label:'Feedback drift',min:-.08,max:.08,step:.001,value:-.006,hint:'Movement along the selected rupture direction while memory decays.'},
 {key:'threshold',label:'Ink threshold',min:0,max:1,step:.01,value:.5,hint:'Black and white print separation point.'},
 {key:'surfaceDamage',label:'Surface damage',min:0,max:1,step:.01,value:.64,hint:'Dry ink, grain and direction-aware material erosion.'},
 {key:'fiberAmount',label:'Dry fiber',min:0,max:1,step:.01,value:.72,hint:'Anisotropic paper and brush fibers cutting through printed areas.'},
 {key:'microDetail',label:'Micro detail',min:0,max:1,step:.01,value:.78,hint:'Fine toner grain, stipple and sub-band breakup.'},
 {key:'detailRecovery',label:'Photo detail',min:0,max:1,step:.01,value:.68,hint:'Recover source tone and local edges inside the damaged print.'},
 {key:'microEchoes',label:'Micro echoes',min:0,max:1,step:.01,value:.72,hint:'Fine repeated fragments remain locked to one directional scanline and decay along it.'},
 {key:'echoDecay',label:'Echo degeneration',min:0,max:1,step:.01,value:.58,hint:'How rapidly consecutive micro echoes lose density and break into perforations.'},
 {key:'glitchGrain',label:'Rupture dirt',min:0,max:1,step:.01,value:.76,hint:'Hard dirt masks perforate only displaced, smeared and echoed image material.'},
 {key:'erosionHardness',label:'Erosion hardness',min:0,max:1,step:.01,value:.84,hint:'Moves rupture dirt from soft granular breakup toward binary toner loss.'},
 {key:'accentAmount',label:'Accent signal',min:0,max:1,step:.01,value:.48,hint:'Amount of the selected spot-color signal layer.'},
 {key:'accentBloom',label:'Ruptured bloom',min:0,max:1,step:.01,value:.54,hint:'Bleeding spot-color halo whose density is broken by the rupture dirt field.'},
 {key:'bloomSpread',label:'Bloom spread',min:0,max:1,step:.01,value:.38,hint:'Cross-directional reach and displaced afterimage of the ruptured accent bloom.'},
 {key:'xeroxStrips',label:'Xerox strips',min:0,max:1,step:.01,value:.46,hint:'Animated directional regions repeatedly copy material from the temporal buffer.'},
 {key:'xeroxGenerations',label:'Copy generations',min:1,max:6,step:1,value:3,hint:'Number of progressively damaged photocopy recurrences sampled per strip.'},
 {key:'xeroxDrift',label:'Copy misregister',min:0,max:.08,step:.001,value:.014,hint:'Directional registration error accumulated by successive copy generations.'},
 {key:'xeroxDecay',label:'Copy degeneration',min:0,max:1,step:.01,value:.64,hint:'Contrast loss, grain dropout and perforation added on every recurrence.'},
 {key:'flowInfluence',label:'Motion influence',min:0,max:1,step:.01,value:.34,hint:'Frame difference drives tear and feedback placement; a web stand-in for optical flow.'},
 {key:'evolution',label:'Evolution rate',min:0,max:4,step:.05,value:1,hint:'Rate at which rupture events change.'},
 {key:'seed',label:'Random seed',min:0,max:9999,step:1,value:71,hint:'Reproducible band and surface arrangement.'},
 {key:'amount',label:'Amount',min:0,max:1,step:.01,value:1,hint:'Blend the complete effect with the source.'}
];
export const defaults=Object.fromEntries(fields.map(f=>[f.key,f.value]));
export const defaultColors={ink:'#e8e4d8',accent:'#ff2638'};
export function defaultRoutes(){
 return [1,1,1,1,1,-1,-1,1,1].map(influence=>[influence,0]);
}
const routeProfiles={
 portrait:[.82,1,.88,.74,.9,-.72,-.55,.68,.62],
 negative:[-.58,-1,-.84,-.66,.72,1,.78,-.7,-.45],
 memorySplit:[.42,.88,.71,.82,1,-1,-.38,.46,.64],
 surfaceEtch:[.22,.36,.18,.12,.28,-.31,1,.16,.08],
 echoContour:[.36,.72,.54,.92,.81,-.86,-.22,.34,.2],
 accentCut:[.28,.66,.48,.4,.55,-.58,.2,1,.36],
 accentInverse:[.25,.55,.42,.31,.5,-.6,.15,-1,.3],
 motionMatte:[.4,.9,.78,.66,1,-.82,.18,.52,1],
 soft:[.18,.32,.26,.2,.38,-.42,.48,.25,.14]
};
const presetRouteProfile={
 'paper-signal':'portrait','xerox-wake':'memorySplit','dry-ink-body':'surfaceEtch','redline-collapse':'accentCut','motion-residue':'motionMatte',
 'carbon-transfer':'negative','echo-register':'echoContour','offset-wound':'portrait','dust-channel':'surfaceEtch','signal-suture':'accentCut',
 'black-archive':'memorySplit','pale-repeater':'soft','blood-fax':'accentInverse','neon-scar':'accentCut','ash-memory':'motionMatte',
 'microfilm-failure':'echoContour','red-fog-register':'accentInverse','severed-broadcast':'motionMatte','cyanotype-fracture':'portrait',
 'sulfur-copy':'negative','cobalt-relay':'motionMatte','magenta-carbon':'echoContour','phosphor-mold':'surfaceEtch',
 'amber-misprint':'memorySplit','violet-archive':'negative','oxidized-sepia':'surfaceEtch',
 'column-shear':'portrait','orthogonal-memory':'memorySplit','diagonal-press':'surfaceEtch','counterflow-copy':'echoContour','falling-carbon':'negative',
 'sideways-bloom':'accentCut','woven-failure':'motionMatte','split-axis':'memorySplit','diagonal-echoes':'echoContour','crossed-cyan':'accentInverse'
};
const presetDirectionProfile={
 'column-shear':[0,90,90,90,90,90,90,90,90],
 'orthogonal-memory':[0,0,0,0,90,90,0,-90,0],
 'diagonal-press':[0,45,45,45,-45,-45,45,-45,45],
 'counterflow-copy':[0,-35,35,-35,70,-70,20,55,-55],
 'falling-carbon':[0,90,90,90,45,-90,90,0,90],
 'sideways-bloom':[0,0,0,0,0,45,0,90,0],
 'woven-failure':[0,0,90,90,-90,90,0,-90,90],
 'split-axis':[0,-60,60,30,-30,90,-45,75,-75],
 'diagonal-echoes':[0,25,25,65,-65,-25,45,0,25],
 'crossed-cyan':[0,90,0,90,45,-45,-90,90,0]
};
function routesForPreset(id){const influence=routeProfiles[presetRouteProfile[id]||'portrait'],angles=presetDirectionProfile[id]||Array(9).fill(0);return influence.map((value,index)=>[value,angles[index]]);}
const presetLibrary=[
 {id:'paper-signal',name:'Paper Signal',style:'transmission',description:'Bleached portrait fragments, horizontal sync loss and a restrained red signal layer.',params:{...defaults},colors:{...defaultColors},routes:defaultRoutes(),combine:'max'},
 {id:'xerox-wake',name:'Xerox Wake',style:'xerox',description:'Dense toner breakup with long copied memories held behind the subject.',params:{...defaults,tearAmount:.42,bandScale:156,tearComplexity:.9,smearLength:.31,waveAmount:.008,feedback:.95,threshold:.57,surfaceDamage:.94,fiberAmount:.86,microDetail:.98,detailRecovery:.45,microEchoes:.94,echoDecay:.72,glitchGrain:.96,erosionHardness:.93,accentAmount:.12,xeroxStrips:.92,xeroxGenerations:6,xeroxDrift:.021,xeroxDecay:.78,flowInfluence:.16},colors:{ink:'#f2eee3',accent:'#ff3344'},routes:defaultRoutes(),combine:'max'},
 {id:'dry-ink-body',name:'Dry Ink Body',style:'dry-ink',description:'Coarse fibrous erosion stays on the subject while its feedback escapes into the surround.',params:{...defaults,tearAmount:.34,bandScale:74,tearComplexity:.82,smearLength:.14,feedback:.86,threshold:.46,surfaceDamage:1,fiberAmount:1,microDetail:.86,detailRecovery:.62,glitchGrain:1,erosionHardness:.78,accentAmount:.28},colors:{ink:'#d8d0bb',accent:'#d92b35'},routes:defaultRoutes(),combine:'max'},
 {id:'redline-collapse',name:'Redline Collapse',style:'thermal',description:'Wide broken bands and hot red timing traces interrupt a scorched monochrome print.',params:{...defaults,tearAmount:.82,bandScale:42,tearComplexity:.94,smearLength:.38,waveAmount:.036,feedback:.89,threshold:.63,surfaceDamage:.79,fiberAmount:.7,microDetail:.72,detailRecovery:.74,microEchoes:.82,echoDecay:.46,glitchGrain:.88,erosionHardness:.9,accentAmount:.92,accentBloom:.9,bloomSpread:.67,flowInfluence:.42},colors:{ink:'#f0d8b6',accent:'#ff182c'},routes:defaultRoutes(),combine:'max'},
 {id:'motion-residue',name:'Motion Residue',style:'motion',description:'Frame difference becomes a provisional motion field for persistent moving ruptures.',params:{...defaults,tearAmount:.73,bandScale:118,smearLength:.26,feedback:.975,feedbackDrift:.014,surfaceDamage:.42,accentAmount:.26,flowInfluence:.96,evolution:1.5},colors:{ink:'#dbe7e1',accent:'#ff3154'},routes:defaultRoutes(),combine:'max'},
 {id:'carbon-transfer',name:'Carbon Transfer',style:'dry-ink',description:'A dense carbon copy with blunt displaced masses, crushed midtones and hard missing toner.',params:{...defaults,tearAmount:.57,bandScale:58,tearComplexity:.88,smearLength:.24,waveAmount:.006,feedback:.84,feedbackDrift:-.012,threshold:.4,surfaceDamage:.97,fiberAmount:.91,microDetail:.93,detailRecovery:.34,microEchoes:.55,echoDecay:.76,glitchGrain:1,erosionHardness:.97,accentAmount:.05,flowInfluence:.12,evolution:.55},colors:{ink:'#d9d4c7',accent:'#b51f2c'},routes:defaultRoutes(),combine:'max'},
 {id:'echo-register',name:'Echo Register',style:'xerox',description:'Fine same-height repetitions dominate while the primary image remains comparatively legible.',params:{...defaults,tearAmount:.29,bandScale:194,tearComplexity:.96,smearLength:.075,waveAmount:.004,feedback:.78,feedbackDrift:-.002,threshold:.52,surfaceDamage:.58,fiberAmount:.49,microDetail:.96,detailRecovery:.81,microEchoes:1,echoDecay:.34,glitchGrain:.7,erosionHardness:.88,accentAmount:.18,flowInfluence:.08,evolution:.7},colors:{ink:'#eeeae0',accent:'#ff293c'},routes:defaultRoutes(),combine:'max'},
 {id:'offset-wound',name:'Offset Wound',style:'transmission',description:'A few broad image sections shear vertically from their origin and leave sparse red registration wounds.',params:{...defaults,tearAmount:.93,bandScale:21,tearComplexity:.79,directionAngle:90,crossAmount:.12,smearLength:.46,waveAmount:.012,feedback:.72,feedbackDrift:-.026,threshold:.49,surfaceDamage:.74,fiberAmount:.67,microDetail:.62,detailRecovery:.79,microEchoes:.38,echoDecay:.69,glitchGrain:.86,erosionHardness:.91,accentAmount:.82,flowInfluence:.22,evolution:.42},colors:{ink:'#e5dfd1',accent:'#ff1b2e'},routes:defaultRoutes(),combine:'max'},
 {id:'dust-channel',name:'Dust Channel',style:'dry-ink',description:'The displacement stays restrained while dirt, fibers and pinholes eat deeply into every copied fragment.',params:{...defaults,tearAmount:.26,bandScale:132,tearComplexity:.71,smearLength:.11,waveAmount:.003,feedback:.66,feedbackDrift:.003,threshold:.44,surfaceDamage:1,fiberAmount:1,microDetail:1,detailRecovery:.55,microEchoes:.68,echoDecay:.83,glitchGrain:1,erosionHardness:1,accentAmount:.09,flowInfluence:.05,evolution:.3},colors:{ink:'#cfc9b9',accent:'#d22635'},routes:defaultRoutes(),combine:'max'},
 {id:'signal-suture',name:'Signal Suture',style:'thermal',description:'Thin red timing sutures cross pale, sharply eroded bands with minimal temporal residue.',params:{...defaults,tearAmount:.48,bandScale:173,tearComplexity:.91,smearLength:.17,waveAmount:.021,feedback:.39,feedbackDrift:.007,threshold:.61,surfaceDamage:.69,fiberAmount:.58,microDetail:.89,detailRecovery:.72,microEchoes:.76,echoDecay:.63,glitchGrain:.79,erosionHardness:.95,accentAmount:1,accentBloom:.76,bloomSpread:.29,flowInfluence:.17,evolution:1.2},colors:{ink:'#f3e9d7',accent:'#ff1028'},routes:defaultRoutes(),combine:'max'},
 {id:'black-archive',name:'Black Archive',style:'xerox',description:'Long-lived fragments accumulate into a dark archival field while the current image survives in damaged islands.',params:{...defaults,tearAmount:.69,bandScale:83,tearComplexity:.9,smearLength:.34,waveAmount:.009,feedback:.99,feedbackDrift:-.019,threshold:.67,surfaceDamage:.9,fiberAmount:.83,microDetail:.84,detailRecovery:.42,microEchoes:.87,echoDecay:.51,glitchGrain:.92,erosionHardness:.86,accentAmount:.21,xeroxStrips:.76,xeroxGenerations:5,xeroxDrift:.034,xeroxDecay:.55,flowInfluence:.47,evolution:.85},colors:{ink:'#ddd8cc',accent:'#e12437'},routes:defaultRoutes(),combine:'max'},
 {id:'pale-repeater',name:'Pale Repeater',style:'transmission',description:'A quiet high-detail print broken by delicate repeated contours and lightly abraded scanlines.',params:{...defaults,tearAmount:.2,bandScale:216,tearComplexity:.84,smearLength:.045,waveAmount:.002,feedback:.58,feedbackDrift:-.001,threshold:.37,surfaceDamage:.38,fiberAmount:.36,microDetail:.82,detailRecovery:1,microEchoes:.92,echoDecay:.27,glitchGrain:.43,erosionHardness:.72,accentAmount:.11,accentBloom:.18,bloomSpread:.14,flowInfluence:.03,evolution:.24},colors:{ink:'#f2efe7',accent:'#f02b3b'},routes:defaultRoutes(),combine:'max'},
 {id:'blood-fax',name:'Blood Fax',style:'xerox',description:'A crushed fax transfer cut by saturated red bloom that leaks through missing toner.',params:{...defaults,tearAmount:.64,bandScale:146,tearComplexity:.93,smearLength:.27,waveAmount:.007,feedback:.93,feedbackDrift:-.011,threshold:.64,surfaceDamage:.96,fiberAmount:.92,microDetail:1,detailRecovery:.31,microEchoes:.86,echoDecay:.68,glitchGrain:1,erosionHardness:.96,accentAmount:1,accentBloom:1,bloomSpread:.72,xeroxStrips:.84,xeroxGenerations:4,xeroxDrift:.018,xeroxDecay:.87,flowInfluence:.2,evolution:.76},colors:{ink:'#ded8cb',accent:'#ff0924'},routes:defaultRoutes(),combine:'max'},
 {id:'neon-scar',name:'Neon Scar',style:'thermal',description:'Sparse ivory fragments are crossed by a narrow fluorescent scar with a sharply ruptured halo.',params:{...defaults,tearAmount:.41,bandScale:107,tearComplexity:.87,smearLength:.13,waveAmount:.016,feedback:.68,feedbackDrift:.005,threshold:.59,surfaceDamage:.66,fiberAmount:.54,microDetail:.78,detailRecovery:.84,microEchoes:.49,echoDecay:.74,glitchGrain:.82,erosionHardness:1,accentAmount:1,accentBloom:.88,bloomSpread:.22,flowInfluence:.11,evolution:1.35},colors:{ink:'#eee6d5',accent:'#ff164f'},routes:defaultRoutes(),combine:'max'},
 {id:'ash-memory',name:'Ash Memory',style:'motion',description:'Soft moving remains accumulate like ash while faint crimson blooms survive at their torn edges.',params:{...defaults,tearAmount:.52,bandScale:69,tearComplexity:.74,smearLength:.22,waveAmount:.01,feedback:.988,feedbackDrift:.018,threshold:.47,surfaceDamage:.88,fiberAmount:.95,microDetail:.71,detailRecovery:.58,microEchoes:.62,echoDecay:.81,glitchGrain:.91,erosionHardness:.7,accentAmount:.34,accentBloom:.79,bloomSpread:.81,flowInfluence:1,evolution:.62},colors:{ink:'#c9c6bc',accent:'#c92b3b'},routes:defaultRoutes(),combine:'max'},
 {id:'microfilm-failure',name:'Microfilm Failure',style:'transmission',description:'Extremely fine archival scanlines, pinhole decay and restrained repeating registration marks.',params:{...defaults,tearAmount:.24,bandScale:220,tearComplexity:1,smearLength:.06,waveAmount:.003,feedback:.81,feedbackDrift:-.002,threshold:.55,surfaceDamage:.82,fiberAmount:.76,microDetail:1,detailRecovery:.91,microEchoes:1,echoDecay:.39,glitchGrain:.93,erosionHardness:.98,accentAmount:.26,accentBloom:.42,bloomSpread:.18,xeroxStrips:.61,xeroxGenerations:5,xeroxDrift:.006,xeroxDecay:.93,flowInfluence:.04,evolution:.2},colors:{ink:'#e7e2d6',accent:'#ed3040'},routes:defaultRoutes(),combine:'max'},
 {id:'red-fog-register',name:'Red Fog Register',style:'thermal',description:'Broad displaced color exposure hangs around slow black ruptures like contaminated print chemistry.',params:{...defaults,tearAmount:.77,bandScale:34,tearComplexity:.81,smearLength:.36,waveAmount:.029,feedback:.96,feedbackDrift:-.021,threshold:.56,surfaceDamage:.72,fiberAmount:.63,microDetail:.65,detailRecovery:.69,microEchoes:.44,echoDecay:.53,glitchGrain:.7,erosionHardness:.61,accentAmount:.9,accentBloom:1,bloomSpread:1,flowInfluence:.36,evolution:.38},colors:{ink:'#e4d5bf',accent:'#e51e35'},routes:defaultRoutes(),combine:'max'},
 {id:'severed-broadcast',name:'Severed Broadcast',style:'motion',description:'Fast crossed tears, long deposits and unstable red blooms produce a violent transmission failure.',params:{...defaults,tearAmount:1,bandScale:91,tearComplexity:1,directionAngle:0,crossAmount:.82,smearLength:.5,waveAmount:.056,feedback:.98,feedbackDrift:.036,threshold:.6,surfaceDamage:.86,fiberAmount:.73,microDetail:.9,detailRecovery:.51,microEchoes:.95,echoDecay:.43,glitchGrain:.96,erosionHardness:.89,accentAmount:.82,accentBloom:.94,bloomSpread:.64,flowInfluence:1,evolution:2.4},colors:{ink:'#dce2dc',accent:'#ff1739'},routes:defaultRoutes(),combine:'add'},
 {id:'cyanotype-fracture',name:'Cyanotype Fracture',style:'transmission',description:'Cold cyan paper exposure fractures into dark blue register echoes and watery copied edges.',params:{...defaults,tearAmount:.58,bandScale:88,tearComplexity:.86,smearLength:.23,waveAmount:.014,feedback:.9,feedbackDrift:-.01,threshold:.51,surfaceDamage:.68,fiberAmount:.72,microDetail:.83,detailRecovery:.73,microEchoes:.71,echoDecay:.6,glitchGrain:.78,erosionHardness:.82,accentAmount:.72,accentBloom:.76,bloomSpread:.55,xeroxStrips:.59,xeroxGenerations:4,xeroxDrift:.016,xeroxDecay:.67,flowInfluence:.21,evolution:.73},colors:{ink:'#c9e8e5',accent:'#00bfe8'},routes:defaultRoutes(),combine:'max'},
 {id:'sulfur-copy',name:'Sulfur Copy',style:'dry-ink',description:'Dirty sulfur-yellow registration burns through a dense charcoal photocopy with brittle hard erosion.',params:{...defaults,tearAmount:.47,bandScale:127,tearComplexity:.91,smearLength:.18,waveAmount:.005,feedback:.82,feedbackDrift:.006,threshold:.6,surfaceDamage:1,fiberAmount:.96,microDetail:.95,detailRecovery:.4,microEchoes:.79,echoDecay:.73,glitchGrain:1,erosionHardness:1,accentAmount:.86,accentBloom:.69,bloomSpread:.31,xeroxStrips:.83,xeroxGenerations:5,xeroxDrift:.012,xeroxDecay:.84,flowInfluence:.09,evolution:.48},colors:{ink:'#d4d0bd',accent:'#f2d900'},routes:defaultRoutes(),combine:'max'},
 {id:'cobalt-relay',name:'Cobalt Relay',style:'motion',description:'Deep cobalt vertical signal wounds follow motion and accumulate behind pale blue-grey image fragments.',params:{...defaults,tearAmount:.7,bandScale:103,tearComplexity:.89,directionAngle:90,crossAmount:.18,smearLength:.3,waveAmount:.025,feedback:.975,feedbackDrift:.022,threshold:.54,surfaceDamage:.61,fiberAmount:.57,microDetail:.77,detailRecovery:.76,microEchoes:.65,echoDecay:.56,glitchGrain:.72,erosionHardness:.8,accentAmount:.94,accentBloom:.88,bloomSpread:.7,xeroxStrips:.52,xeroxGenerations:3,xeroxDrift:.029,xeroxDecay:.48,flowInfluence:.92,evolution:1.3},colors:{ink:'#cbd8e2',accent:'#245dff'},routes:defaultRoutes(),combine:'add'},
 {id:'magenta-carbon',name:'Magenta Carbon',style:'xerox',description:'High-density carbon generations split into electric magenta halos and fine repeated contours.',params:{...defaults,tearAmount:.55,bandScale:171,tearComplexity:.98,smearLength:.2,waveAmount:.008,feedback:.95,feedbackDrift:-.014,threshold:.62,surfaceDamage:.91,fiberAmount:.84,microDetail:1,detailRecovery:.49,microEchoes:1,echoDecay:.52,glitchGrain:.93,erosionHardness:.94,accentAmount:1,accentBloom:1,bloomSpread:.47,xeroxStrips:.94,xeroxGenerations:6,xeroxDrift:.02,xeroxDecay:.71,flowInfluence:.18,evolution:.88},colors:{ink:'#e5d9e3',accent:'#ff1bbd'},routes:defaultRoutes(),combine:'max'},
 {id:'phosphor-mold',name:'Phosphor Mold',style:'thermal',description:'Sickly phosphor residue blooms through diagonal fibers and slow organic feedback damage.',params:{...defaults,tearAmount:.39,bandScale:62,tearComplexity:.74,directionAngle:-32,crossAmount:.34,smearLength:.16,waveAmount:.031,feedback:.96,feedbackDrift:.009,threshold:.46,surfaceDamage:.93,fiberAmount:1,microDetail:.7,detailRecovery:.57,microEchoes:.48,echoDecay:.82,glitchGrain:.97,erosionHardness:.68,accentAmount:.81,accentBloom:1,bloomSpread:.92,xeroxStrips:.43,xeroxGenerations:4,xeroxDrift:.01,xeroxDecay:.76,flowInfluence:.34,evolution:.29},colors:{ink:'#d7dfc8',accent:'#74ef3a'},routes:defaultRoutes(),combine:'max'},
 {id:'amber-misprint',name:'Amber Misprint',style:'thermal',description:'Warm amber registration slips across scorched paper strips with restrained multi-copy degeneration.',params:{...defaults,tearAmount:.63,bandScale:47,tearComplexity:.83,smearLength:.33,waveAmount:.019,feedback:.87,feedbackDrift:-.023,threshold:.57,surfaceDamage:.79,fiberAmount:.7,microDetail:.75,detailRecovery:.68,microEchoes:.59,echoDecay:.66,glitchGrain:.84,erosionHardness:.87,accentAmount:.92,accentBloom:.85,bloomSpread:.59,xeroxStrips:.68,xeroxGenerations:3,xeroxDrift:.038,xeroxDecay:.58,flowInfluence:.26,evolution:.56},colors:{ink:'#e4d2b7',accent:'#ff941a'},routes:defaultRoutes(),combine:'max'},
 {id:'violet-archive',name:'Violet Archive',style:'xerox',description:'A cool violet archive traps thin copy generations inside long-lived dark feedback bands.',params:{...defaults,tearAmount:.46,bandScale:154,tearComplexity:.94,smearLength:.15,waveAmount:.006,feedback:.992,feedbackDrift:-.008,threshold:.66,surfaceDamage:.87,fiberAmount:.81,microDetail:.92,detailRecovery:.46,microEchoes:.91,echoDecay:.44,glitchGrain:.9,erosionHardness:.91,accentAmount:.68,accentBloom:.73,bloomSpread:.39,xeroxStrips:.88,xeroxGenerations:6,xeroxDrift:.011,xeroxDecay:.62,flowInfluence:.31,evolution:.41},colors:{ink:'#ddd8e4',accent:'#a64dff'},routes:defaultRoutes(),combine:'max'},
 {id:'oxidized-sepia',name:'Oxidized Sepia',style:'dry-ink',description:'Faded warm ink, copper oxidation and abrasive copy loss evoke a damaged mechanical archive.',params:{...defaults,tearAmount:.35,bandScale:96,tearComplexity:.8,smearLength:.12,waveAmount:.004,feedback:.76,feedbackDrift:.004,threshold:.43,surfaceDamage:.98,fiberAmount:1,microDetail:.89,detailRecovery:.66,microEchoes:.7,echoDecay:.79,glitchGrain:1,erosionHardness:.92,accentAmount:.64,accentBloom:.58,bloomSpread:.26,xeroxStrips:.72,xeroxGenerations:4,xeroxDrift:.009,xeroxDecay:.88,flowInfluence:.07,evolution:.22},colors:{ink:'#d5b991',accent:'#b85c2d'},routes:defaultRoutes(),combine:'max'},
 {id:'column-shear',name:'Column Shear',style:'transmission',description:'The mask binds vertical tears, downward smears and columnar feedback to the subject while the global look stays horizontal.',params:{...defaults,tearAmount:.82,bandScale:73,tearComplexity:.9,smearLength:.39,waveAmount:.017,feedback:.91,feedbackDrift:.019,surfaceDamage:.67,microEchoes:.64,glitchGrain:.82,accentAmount:.38,xeroxStrips:.58,xeroxGenerations:4,flowInfluence:.32,evolution:.68},colors:{ink:'#e8e4d8',accent:'#ff2638'},routes:defaultRoutes(),combine:'max'},
 {id:'orthogonal-memory',name:'Orthogonal Memory',style:'xerox',description:'Horizontal live rupture writes into a vertical feedback and Xerox memory field with a counter-rotated accent.',params:{...defaults,tearAmount:.6,bandScale:112,tearComplexity:.94,smearLength:.24,feedback:.989,feedbackDrift:-.028,threshold:.61,surfaceDamage:.86,microEchoes:.89,glitchGrain:.93,accentAmount:.57,accentBloom:.74,xeroxStrips:.9,xeroxGenerations:6,xeroxDrift:.027,xeroxDecay:.69,evolution:.52},colors:{ink:'#dfdbd0',accent:'#ff2847'},routes:defaultRoutes(),combine:'max'},
 {id:'diagonal-press',name:'Diagonal Press',style:'dry-ink',description:'Ink fibers, tears and copy scars split across opposing forty-five-degree press directions.',params:{...defaults,tearAmount:.51,bandScale:138,tearComplexity:.87,crossAmount:.24,smearLength:.18,waveAmount:.009,feedback:.79,threshold:.45,surfaceDamage:1,fiberAmount:1,microDetail:.96,detailRecovery:.53,microEchoes:.71,glitchGrain:1,erosionHardness:.95,accentAmount:.29,xeroxStrips:.66,evolution:.36},colors:{ink:'#d8d0bb',accent:'#e33a2f'},routes:defaultRoutes(),combine:'max'},
 {id:'counterflow-copy',name:'Counterflow Copy',style:'xerox',description:'Every masked subsystem pulls against its neighbor, producing opposing copy generations and fractured directional echoes.',params:{...defaults,tearAmount:.67,bandScale:165,tearComplexity:1,crossAmount:.18,smearLength:.29,waveAmount:.014,feedback:.96,feedbackDrift:.031,threshold:.58,surfaceDamage:.88,microEchoes:1,echoDecay:.49,glitchGrain:.9,accentAmount:.42,accentBloom:.65,xeroxStrips:1,xeroxGenerations:6,xeroxDrift:.035,xeroxDecay:.73,evolution:.93},colors:{ink:'#e3ded2',accent:'#f31d67'},routes:defaultRoutes(),combine:'max'},
 {id:'falling-carbon',name:'Falling Carbon',style:'dry-ink',description:'Inverse mask routing lets dense carbon fragments fall vertically while memory rises in the opposite direction.',params:{...defaults,tearAmount:.74,bandScale:54,tearComplexity:.84,directionAngle:0,smearLength:.43,waveAmount:.007,feedback:.94,feedbackDrift:-.022,threshold:.41,surfaceDamage:.98,fiberAmount:.95,microDetail:.87,detailRecovery:.37,microEchoes:.53,glitchGrain:1,erosionHardness:.98,accentAmount:.12,xeroxStrips:.78,xeroxGenerations:5,evolution:.44},colors:{ink:'#cfc9bd',accent:'#cc342b'},routes:defaultRoutes(),combine:'max'},
 {id:'sideways-bloom',name:'Sideways Bloom',style:'thermal',description:'The image remains horizontally ruptured while the masked spot-color signal blooms vertically through it.',params:{...defaults,tearAmount:.48,bandScale:128,tearComplexity:.91,smearLength:.16,waveAmount:.02,feedback:.73,threshold:.6,surfaceDamage:.7,microEchoes:.68,glitchGrain:.8,accentAmount:1,accentBloom:1,bloomSpread:.88,xeroxStrips:.37,flowInfluence:.19,evolution:1.08},colors:{ink:'#eee4d4',accent:'#ff183b'},routes:defaultRoutes(),combine:'max'},
 {id:'woven-failure',name:'Woven Failure',style:'motion',description:'Alternating horizontal and vertical mask directions weave moving tears, smears, feedback and signal color together.',params:{...defaults,tearAmount:.86,bandScale:97,tearComplexity:.98,crossAmount:.61,smearLength:.36,waveAmount:.038,feedback:.978,feedbackDrift:.025,surfaceDamage:.81,microEchoes:.91,glitchGrain:.9,accentAmount:.76,accentBloom:.82,xeroxStrips:.7,xeroxGenerations:4,flowInfluence:1,evolution:1.7},colors:{ink:'#d8e2dd',accent:'#60e8ff'},routes:defaultRoutes(),combine:'add'},
 {id:'split-axis',name:'Split Axis',style:'motion',description:'Nine independently angled mask destinations pull one source into a deliberately unstable multi-axis feedback structure.',params:{...defaults,tearAmount:.9,bandScale:82,tearComplexity:1,crossAmount:.43,smearLength:.41,waveAmount:.044,feedback:.985,feedbackDrift:-.034,threshold:.55,surfaceDamage:.84,microEchoes:.88,glitchGrain:.94,accentAmount:.83,accentBloom:.91,bloomSpread:.73,xeroxStrips:.82,xeroxGenerations:5,flowInfluence:.92,evolution:1.9},colors:{ink:'#e1dcd4',accent:'#b24cff'},routes:defaultRoutes(),combine:'add'},
 {id:'diagonal-echoes',name:'Diagonal Echoes',style:'transmission',description:'Fine mask-bound echoes travel diagonally while feedback and Xerox recurrence return along a counter-axis.',params:{...defaults,tearAmount:.38,bandScale:207,tearComplexity:1,smearLength:.12,waveAmount:.006,feedback:.9,feedbackDrift:.011,threshold:.49,surfaceDamage:.63,microDetail:1,detailRecovery:.84,microEchoes:1,echoDecay:.31,glitchGrain:.71,accentAmount:.24,xeroxStrips:.75,xeroxGenerations:5,xeroxDrift:.012,xeroxDecay:.82,evolution:.33},colors:{ink:'#f0ece3',accent:'#ff9b21'},routes:defaultRoutes(),combine:'max'},
 {id:'crossed-cyan',name:'Crossed Cyan',style:'thermal',description:'An inverse cyan accent crosses vertical smear and surface axes while memory recedes diagonally.',params:{...defaults,tearAmount:.65,bandScale:119,tearComplexity:.93,crossAmount:.52,smearLength:.28,waveAmount:.026,feedback:.95,feedbackDrift:.017,threshold:.57,surfaceDamage:.77,microEchoes:.76,glitchGrain:.86,accentAmount:1,accentBloom:.96,bloomSpread:.65,xeroxStrips:.63,xeroxGenerations:4,flowInfluence:.48,evolution:.86},colors:{ink:'#d6e4e2',accent:'#00d5ff'},routes:defaultRoutes(),combine:'max'}
];
export const presets=presetLibrary.map(preset=>({...preset,routes:routesForPreset(preset.id)}));
const combineModes=['max','add','multiply','min'],styles=['transmission','xerox','dry-ink','thermal','motion'];
export function validateRoutes(routes){
 if(!Array.isArray(routes)||routes.length!==destinations.length)throw new Error('Invalid mask routing row count.');
 return routes.map(route=>{
  // Version-1 matrix migration: A maps normally, B was A inverted; procedural C/D routes become unmasked.
  if(Array.isArray(route)&&route.length===4){if(route.some(value=>value!==-1&&value!==0&&value!==1))throw new Error('Invalid legacy mask routing cell.');route=[route[0]||-route[1]||0,0];}
  else if(typeof route==='number')route=[route,0];
  if(!Array.isArray(route)||route.length!==2||route.some(value=>typeof value!=='number'||!Number.isFinite(value))||route[0]< -1||route[0]>1||route[1]< -90||route[1]>90)throw new Error('Invalid mask XY routing value.');
  return [...route];
 });
}
export function parsePreset(text){
 const value=JSON.parse(text);
 if(value?.format!=='raster-rupture-preset'||value.version!==1)throw new Error('Expected a RASTER RUPTURE version 1 preset.');
 if(!styles.includes(value.style))throw new Error('Invalid style.');
 if(!combineModes.includes(value.combine))throw new Error('Invalid mask combine mode.');
 const params={};
 for(const field of fields){
  const n=value.params?.[field.key];
  if(typeof n!=='number'||!Number.isFinite(n)||n<field.min||n>field.max||(field.step===1&&!Number.isInteger(n)))throw new Error('Invalid parameter: '+field.label);
  params[field.key]=n;
 }
 const colors=value.colors??defaultColors;if(!/^#[0-9a-f]{6}$/i.test(colors.ink)||!/^#[0-9a-f]{6}$/i.test(colors.accent))throw new Error('Invalid effect color.');
 return {format:value.format,version:1,name:typeof value.name==='string'&&value.name.trim()?value.name.trim().slice(0,80):'Untitled',style:value.style,description:typeof value.description==='string'?value.description.slice(0,300):'',params,colors:{ink:colors.ink.toLowerCase(),accent:colors.accent.toLowerCase()},routes:validateRoutes(value.routes),combine:value.combine};
}
export function serializePreset({name,style,description,params,colors=defaultColors,routes,combine='max'}){
 return parsePreset(JSON.stringify({format:'raster-rupture-preset',version:1,name,style,description,params:{...params},colors:{...colors},routes,combine}));
}
export function nextPreset(ids,current,delta){const at=Math.max(0,ids.indexOf(current));return ids[(at+delta+ids.length)%ids.length];}
export function previewSize(width,height){const scale=Math.min(1,1920/width,1080/height);return {width:Math.max(1,Math.round(width*scale)),height:Math.max(1,Math.round(height*scale))};}
