#include "raster_rupture/core.hpp"
#include <cuda_runtime.h>
#include "core_math.cuh"
namespace raster_rupture { namespace {
__global__ void kernel(RenderRequest request){int x=blockIdx.x*blockDim.x+threadIdx.x,y=blockIdx.y*blockDim.y+threadIdx.y;if(x>=request.source.width||y>=request.source.height)return;detail::renderPixel(request,x,y,request.output.data+(size_t(y)*request.source.width+x)*4);}
bool copyImage(const ConstImageView&src,float*&dst,ConstImageView&device){if(!src.data)return true;size_t bytes=size_t(src.width)*src.height*src.components*sizeof(float);if(cudaMalloc(&dst,bytes)!=cudaSuccess)return false;for(int y=0;y<src.height;y++)if(cudaMemcpy(dst+size_t(y)*src.width*src.components,reinterpret_cast<const unsigned char*>(src.data)+std::ptrdiff_t(y)*src.row_bytes,size_t(src.width)*src.components*sizeof(float),cudaMemcpyHostToDevice)!=cudaSuccess)return false;device={dst,src.width,src.height,src.components,std::ptrdiff_t(src.width*src.components*sizeof(float))};return true;}
}
bool cudaAvailable(){int n=0;return cudaGetDeviceCount(&n)==cudaSuccess&&n>0;}
RenderStatus renderCuda(const RenderRequest&request){if(!cudaAvailable())return RenderStatus::CudaUnavailable;float *source=nullptr,*previous=nullptr,*mask=nullptr,*output=nullptr;RenderRequest d=request;bool ok=copyImage(request.source,source,d.source)&&copyImage(request.previous,previous,d.previous)&&copyImage(request.mask,mask,d.mask)&&cudaMalloc(&output,size_t(request.source.width)*request.source.height*4*sizeof(float))==cudaSuccess;d.output={output,request.source.width,request.source.height,std::ptrdiff_t(request.source.width*16)};if(ok){dim3 block(16,16),grid((request.source.width+15)/16,(request.source.height+15)/16);kernel<<<grid,block>>>(d);ok=cudaGetLastError()==cudaSuccess&&cudaDeviceSynchronize()==cudaSuccess;for(int y=0;ok&&y<request.source.height;y++)ok=cudaMemcpy(reinterpret_cast<unsigned char*>(request.output.data)+std::ptrdiff_t(y)*request.output.row_bytes,output+size_t(y)*request.source.width*4,size_t(request.source.width)*16,cudaMemcpyDeviceToHost)==cudaSuccess;}cudaFree(source);cudaFree(previous);cudaFree(mask);cudaFree(output);return ok?RenderStatus::Ok:RenderStatus::CudaError;}
}
