#include "grid_rot/core.hpp"
#include <cuda_runtime.h>
#include "core_math.cuh"
namespace grid_rot {namespace {
__global__ void kernel(RenderRequest r){int x=blockIdx.x*blockDim.x+threadIdx.x,y=blockIdx.y*blockDim.y+threadIdx.y;if(x<r.source.width&&y<r.source.height)detail::pixel(r,x,y,r.output.data+(size_t(y)*r.source.width+x)*4);}
bool copy(const ConstImageView&s,float*&allocation,ConstImageView&d){if(!s.data)return true;size_t stride=size_t(s.width)*s.components,bytes=stride*s.height*sizeof(float);if(cudaMalloc(&allocation,bytes)!=cudaSuccess)return false;for(int y=0;y<s.height;++y)if(cudaMemcpy(allocation+size_t(y)*stride,reinterpret_cast<const unsigned char*>(s.data)+std::ptrdiff_t(y)*s.row_bytes,stride*sizeof(float),cudaMemcpyHostToDevice)!=cudaSuccess)return false;d={allocation,s.width,s.height,s.components,std::ptrdiff_t(stride*sizeof(float))};return true;}
}
bool cudaAvailable(){int count=0;return cudaGetDeviceCount(&count)==cudaSuccess&&count>0;}
RenderStatus renderCuda(const RenderRequest&input){if(!cudaAvailable())return RenderStatus::CudaUnavailable;RenderRequest r=input;prepare(r);float*source=nullptr,*history=nullptr,*output=nullptr;size_t pixels=size_t(r.source.width)*r.source.height,frameBytes=pixels*4*sizeof(float);bool ok=copy(input.source,source,r.source);r.history[0]=r.source;if(ok&&r.history_count>1){if(cudaMalloc(&history,frameBytes*(r.history_count-1))!=cudaSuccess)ok=false;for(int i=1;ok&&i<r.history_count;++i){for(int y=0;y<input.history[i].height;++y)if(cudaMemcpy(history+size_t(i-1)*pixels+size_t(y)*input.history[i].width*4,reinterpret_cast<const unsigned char*>(input.history[i].data)+std::ptrdiff_t(y)*input.history[i].row_bytes,size_t(input.history[i].width)*16,cudaMemcpyHostToDevice)!=cudaSuccess){ok=false;break;}r.history[i]={history+size_t(i-1)*pixels,input.history[i].width,input.history[i].height,4,std::ptrdiff_t(input.history[i].width*16)};}}if(ok&&cudaMalloc(&output,frameBytes)!=cudaSuccess)ok=false;r.output={output,r.source.width,r.source.height,std::ptrdiff_t(r.source.width*16)};if(ok){dim3 block(16,16),grid((r.source.width+15)/16,(r.source.height+15)/16);kernel<<<grid,block>>>(r);ok=cudaGetLastError()==cudaSuccess&&cudaDeviceSynchronize()==cudaSuccess;for(int y=0;ok&&y<input.output.height;++y)ok=cudaMemcpy(reinterpret_cast<unsigned char*>(input.output.data)+std::ptrdiff_t(y)*input.output.row_bytes,output+size_t(y)*input.output.width*4,size_t(input.output.width)*16,cudaMemcpyDeviceToHost)==cudaSuccess;}cudaFree(source);cudaFree(history);cudaFree(output);return ok?RenderStatus::Ok:RenderStatus::CudaError;}
}