#pragma once
#include <algorithm>
#include <cmath>
#include <cstdint>
#include "grid_rot/core.hpp"
#ifdef __CUDACC__
#define GR_HD __host__ __device__
#else
#define GR_HD
#endif
namespace grid_rot::detail {
GR_HD inline float clampf(float v,float a=0,float b=1){return v<a?a:v>b?b:v;}GR_HD inline float mixf(float a,float b,float t){return a+(b-a)*t;}GR_HD inline float fractf(float v){return v-floorf(v);}GR_HD inline float modf(float a,float b){return a-b*floorf(a/b);}GR_HD inline float noise(float x,float y){return fractf(sinf(x*127.1f+y*311.7f)*43758.5453f);}GR_HD inline float smooth(float a,float b,float v){float t=clampf((v-a)/(b-a));return t*t*(3-2*t);}GR_HD inline float pv(const ParameterValues&v,ParameterId id){return float(v[static_cast<std::size_t>(id)]);}
GR_HD inline const float*row(const ConstImageView&i,int y){return reinterpret_cast<const float*>(reinterpret_cast<const unsigned char*>(i.data)+std::ptrdiff_t(y)*i.row_bytes);}GR_HD inline float channel(const ConstImageView&i,int x,int y,int c){if(!i.data||i.width<1||i.height<1)return c==3?1.f:0.f;x=x<0?0:x>=i.width?i.width-1:x;y=y<0?0:y>=i.height?i.height-1:y;return row(i,y)[x*i.components+(c<i.components?c:i.components-1)];}
struct V2{float x,y;};struct V3{float x,y,z;};GR_HD inline V2 v2(float x,float y){return{x,y};}GR_HD inline V2 add(V2 a,V2 b){return{a.x+b.x,a.y+b.y};}GR_HD inline V2 sub(V2 a,V2 b){return{a.x-b.x,a.y-b.y};}GR_HD inline V2 mul(V2 a,float b){return{a.x*b,a.y*b};}GR_HD inline float length(V2 a){return sqrtf(a.x*a.x+a.y*a.y);}GR_HD inline V3 mixv(V3 a,V3 b,float t){return{mixf(a.x,b.x,t),mixf(a.y,b.y,t),mixf(a.z,b.z,t)};}GR_HD inline V3 sample(const ConstImageView&i,V2 uv){float fx=uv.x*i.width-.5f,fy=uv.y*i.height-.5f;int x0=int(floorf(fx)),y0=int(floorf(fy)),x1=x0+1,y1=y0+1;float tx=fx-x0,ty=fy-y0;V3 a{mixf(channel(i,x0,y0,0),channel(i,x1,y0,0),tx),mixf(channel(i,x0,y0,1),channel(i,x1,y0,1),tx),mixf(channel(i,x0,y0,2),channel(i,x1,y0,2),tx)},b{mixf(channel(i,x0,y1,0),channel(i,x1,y1,0),tx),mixf(channel(i,x0,y1,1),channel(i,x1,y1,1),tx),mixf(channel(i,x0,y1,2),channel(i,x1,y1,2),tx)};return mixv(a,b,ty);}GR_HD inline float luma(V3 c){return c.x*.2126f+c.y*.7152f+c.z*.0722f;}
GR_HD inline float edgeAt(const RenderRequest&r,V2 uv){V2 d{1.5f/r.source.width,1.5f/r.source.height};float x=luma(sample(r.source,{uv.x+d.x,uv.y}))-luma(sample(r.source,{uv.x-d.x,uv.y})),y=luma(sample(r.source,{uv.x,uv.y+d.y}))-luma(sample(r.source,{uv.x,uv.y-d.y}));return sqrtf(x*x+y*y);}GR_HD inline float motionAt(const RenderRequest&r,V2 uv){return r.history_count>1?fabsf(luma(sample(r.source,uv))-luma(sample(r.history[1],uv))):0;}
GR_HD inline ParameterId enabledId(int op){const ParameterId ids[]={ParameterId::OpOffsetEnabled,ParameterId::OpMirrorEnabled,ParameterId::OpRotateEnabled,ParameterId::OpZoomEnabled,ParameterId::OpNeighborEnabled,ParameterId::OpChannelEnabled,ParameterId::OpBlackoutEnabled,ParameterId::OpNoiseEnabled,ParameterId::OpHoldEnabled,ParameterId::OpDelayEnabled,ParameterId::OpStutterEnabled,ParameterId::OpReverseEnabled,ParameterId::OpSmearEnabled};return ids[op];}GR_HD inline ParameterId weightId(int op){const ParameterId ids[]={ParameterId::OpOffsetWeight,ParameterId::OpMirrorWeight,ParameterId::OpRotateWeight,ParameterId::OpZoomWeight,ParameterId::OpNeighborWeight,ParameterId::OpChannelWeight,ParameterId::OpBlackoutWeight,ParameterId::OpNoiseWeight,ParameterId::OpHoldWeight,ParameterId::OpDelayWeight,ParameterId::OpStutterWeight,ParameterId::OpReverseWeight,ParameterId::OpSmearWeight};return ids[op];}GR_HD inline ParameterId strengthId(int op){const ParameterId ids[]={ParameterId::OpOffsetStrength,ParameterId::OpMirrorStrength,ParameterId::OpRotateStrength,ParameterId::OpZoomStrength,ParameterId::OpNeighborStrength,ParameterId::OpChannelStrength,ParameterId::OpBlackoutStrength,ParameterId::OpNoiseStrength,ParameterId::OpHoldStrength,ParameterId::OpDelayStrength,ParameterId::OpStutterStrength,ParameterId::OpReverseStrength,ParameterId::OpSmearStrength};return ids[op];}
GR_HD inline float setting0(const ParameterValues&v,int op){switch(op){case 0:return pv(v,ParameterId::OpOffsetDistance);case 1:return pv(v,ParameterId::OpMirrorAxis);case 2:return pv(v,ParameterId::OpRotateTurns);case 3:return pv(v,ParameterId::OpZoomScale);case 4:return pv(v,ParameterId::OpNeighborRadius);case 5:return pv(v,ParameterId::OpChannelPermutation);case 6:return pv(v,ParameterId::OpBlackoutLevel);case 7:return pv(v,ParameterId::OpNoiseScale);case 9:return pv(v,ParameterId::OpDelayFrames);case 10:return pv(v,ParameterId::OpStutterFrames);case 11:return pv(v,ParameterId::OpReverseFrames);case 12:return pv(v,ParameterId::OpSmearFrames);default:return 1;}}GR_HD inline float setting1(const ParameterValues&v,int op){return op==0?pv(v,ParameterId::OpOffsetAngle):0;}
GR_HD inline int chooseOperator(const ParameterValues&v,V2 cell,float tick){float total=0;for(int i=0;i<kOperatorCount;++i)if(pv(v,enabledId(i))>.5f)total+=pv(v,weightId(i));if(total<=0)return-1;float pick=noise(cell.x+tick*.013f,cell.y+tick*.013f)*total,used=0;for(int i=0;i<kOperatorCount;++i){if(pv(v,enabledId(i))>.5f)used+=pv(v,weightId(i));if(pick<used)return i;}return 12;}
GR_HD inline V2 topologyCell(V2 p,const RenderRequest&r,int type,float jitter){V2 base{floorf(p.x),floorf(p.y)};if(type<2)return{modf(base.x,float(r.grid_columns)),modf(base.y,float(r.grid_rows))};V2 best=base;float bestD=1e20f;for(int y=-1;y<=1;++y)for(int x=-1;x<=1;++x){V2 c{base.x+x,base.y+y},point{c.x+.5f+(noise(c.x+13,c.y+13)-.5f)*jitter,c.y+.5f+(noise(c.x+71,c.y+71)-.5f)*jitter};V2 d=sub(p,point);float q=d.x*d.x+d.y*d.y;if(q<bestD){bestD=q;best=c;}}return{modf(best.x+r.grid_columns,float(r.grid_columns)),modf(best.y+r.grid_rows,float(r.grid_rows))};}
GR_HD inline void pixel(const RenderRequest&r,int x,int y,float*out){const auto&v=r.values;V2 uv{(x+.5f)/r.source.width,(y+.5f)/r.source.height},mapped=uv;int topology=int(pv(v,ParameterId::TopologyType));float jitter=pv(v,ParameterId::TopologyJitter),skew=pv(v,ParameterId::TopologySkew),warp=pv(v,ParameterId::TopologyWarpAmount),warpSpeed=pv(v,ParameterId::TopologyWarpSpeed);mapped.x+=(mapped.y-.5f)*skew;mapped.x+=sinf((mapped.y+float(r.time_seconds)*warpSpeed)*6.283185f)*warp/r.grid_columns;mapped.y+=cosf((mapped.x-float(r.time_seconds)*warpSpeed)*6.283185f)*warp/r.grid_rows;V2 lattice{mapped.x*r.grid_columns,(1-mapped.y)*r.grid_rows};if(topology==0){lattice.x+=(noise(floorf(lattice.y),17)-.5f)*jitter;lattice.y+=(noise(floorf(lattice.x),31)-.5f)*jitter;}V2 cell=topologyCell(lattice,r,topology,jitter);bool affected=false;float strength=0,tick=0;
 for(int i=0;i<r.area_count;++i){const Area&a=r.areas[i];V2 local{modf(cell.x-a.x+r.grid_columns,float(r.grid_columns)),modf(cell.y-a.y+r.grid_rows,float(r.grid_rows))};bool inside=local.x<a.width&&local.y<a.height;V2 half{a.width*.5f,a.height*.5f},center{a.x+half.x,a.y+half.y},wrapped{modf(cell.x-center.x+r.grid_columns*.5f,float(r.grid_columns))-r.grid_columns*.5f,modf(cell.y-center.y+r.grid_rows*.5f,float(r.grid_rows))-r.grid_rows*.5f},outside{fmaxf(fabsf(wrapped.x)-half.x,0),fmaxf(fabsf(wrapped.y)-half.y,0)};int direction=int(pv(v,ParameterId::InfectionDirection));float distance=direction==1?outside.x:direction==2?outside.y:length(outside),radius=pv(v,ParameterId::InfectionRadius),speed=pv(v,ParameterId::InfectionSpeed),decay=pv(v,ParameterId::InfectionDecay),cycle=radius+fmaxf(.001f,speed*decay),phase=modf(float(r.time_seconds)*speed+fmodf(a.tick,65536)*.001f,cycle),infected=pv(v,ParameterId::InfectionAmount)*fmaxf(0,1-distance/fmaxf(.001f,radius))*(distance<=fminf(radius,phase)?1:0)*fmaxf(0,1-fmaxf(0,phase-radius)/fmaxf(.001f,speed*decay)),candidate=inside?a.strength:a.strength*infected;if(candidate>strength){affected=candidate>0;strength=candidate;tick=a.tick;}}
 float scale=1;int depth=int(pv(v,ParameterId::FractureDepth));if(affected)for(int level=1;level<=3&&level<=depth;++level){float seed=fmodf(floorf(tick),997),n=fmodf(cell.x*73+cell.y*151+seed*199+level*37,997),chance=fmodf(n*n+31*n+17,997)/997;if(chance>=pv(v,ParameterId::FractureAmount))break;scale*=2;}V2 fineGrid{r.grid_columns*scale,r.grid_rows*scale};cell={floorf(lattice.x*scale),floorf(lattice.y*scale)};strength=fminf(1,strength*(1+pv(v,ParameterId::InfectionMutation)));
 float lum=luma(sample(r.source,uv)),edge=edgeAt(r,uv),motion=motionAt(r,uv);V2 radius{.28f/r.grid_columns,.28f/r.grid_rows};edge=fmaxf(edge,fmaxf(fmaxf(edgeAt(r,{uv.x+radius.x,uv.y}),edgeAt(r,{uv.x-radius.x,uv.y})),fmaxf(edgeAt(r,{uv.x,uv.y+radius.y}),edgeAt(r,{uv.x,uv.y-radius.y}))));motion=fmaxf(motion,fmaxf(fmaxf(motionAt(r,{uv.x+radius.x,uv.y}),motionAt(r,{uv.x-radius.x,uv.y})),fmaxf(motionAt(r,{uv.x,uv.y+radius.y}),motionAt(r,{uv.x,uv.y-radius.y}))));edge=smooth(.015f,.24f,edge);motion=smooth(.008f,.16f,motion);float uniform=pv(v,ParameterId::TargetingUniform),bright=pv(v,ParameterId::TargetingBright),dark=pv(v,ParameterId::TargetingDark),edges=pv(v,ParameterId::TargetingEdges),motions=pv(v,ParameterId::TargetingMotion),total=uniform+bright+dark+edges+motions,target=total>0?(uniform+bright*lum+dark*(1-lum)+edges*edge+motions*motion)/total:1;strength*=mixf(1,clampf(target),pv(v,ParameterId::TargetingBias));affected=strength>0;V3 fresh=sample(r.source,uv),color=fresh;
 if(affected&&pv(v,ParameterId::Amount)>0){float n=noise(cell.x+floorf(tick)*.137f,cell.y+floorf(tick)*.137f);int op=chooseOperator(v,cell,tick);float os=op<0?0:pv(v,strengthId(op));V2 d{(n-.5f)*2*pv(v,ParameterId::Shift)/fineGrid.x,(noise(cell.x+17,cell.y+17)-.5f)*2*pv(v,ParameterId::Shift)/fineGrid.y},p={uv.x+d.x,uv.y+d.y},origin{floorf(uv.x*fineGrid.x)/fineGrid.x,floorf(uv.y*fineGrid.y)/fineGrid.y},local{fractf(uv.x*fineGrid.x),fractf(uv.y*fineGrid.y)},m=local;if(op==0){float a=setting1(v,op);m=add(m,{cosf(a)*setting0(v,op)*os,sinf(a)*setting0(v,op)*os});}else if(op==1){float axis=setting0(v,op);if(axis<.5f||axis>1.5f)m.x=1-m.x;if(axis>.5f)m.y=1-m.y;}else if(op==2){int turns=int(fmodf(floorf(setting0(v,op)),4));for(int i=0;i<turns;++i)m={1-m.y,m.x};}else if(op==3){float z=fmaxf(.1f,mixf(1,setting0(v,op),os));m={(m.x-.5f)/z+.5f,(m.y-.5f)/z+.5f};}else if(op==4){m.x+=(floorf(noise(cell.x+4,cell.y+4)*3)-1)*setting0(v,op);m.y+=(floorf(noise(cell.x+9,cell.y+9)*3)-1)*setting0(v,op);}if(op>=0&&op<=4)p={origin.x+m.x/fineGrid.x+d.x,origin.y+m.y/fineGrid.y+d.y};V3 damaged=sample(r.source,p);
  if(op>=8&&r.history_count>1){float frames=fmaxf(1,setting0(v,op)),clock=floorf(float(r.frame_number)+.5f),lag=1,blend=0;if(op==8){lag=fmodf(clock,fmaxf(1,pv(v,ParameterId::TemporalRange)));blend=pv(v,ParameterId::TemporalHold);}else if(op==9){lag=frames;blend=pv(v,ParameterId::TemporalDelay);}else if(op==10){lag=fmodf(clock,frames);blend=pv(v,ParameterId::TemporalStutter);}else if(op==11){lag=1+2*fmodf(clock,frames);blend=pv(v,ParameterId::TemporalReverse);}else{lag=1+noise(cell.x,cell.y)*frames;blend=pv(v,ParameterId::TemporalSmear);}int li=int(fminf(floorf(lag),float(r.history_count-1)));V3 temporal=sample(r.history[li],p);if(op==12){int mid=int(fminf(fmaxf(1,floorf(frames*.5f)),float(r.history_count-1))),tail=int(fminf(frames,float(r.history_count-1)));V3 b=sample(r.history[mid],p),c=sample(r.history[tail],p);temporal={(temporal.x+b.x+c.x)/3,(temporal.y+b.y+c.y)/3,(temporal.z+b.z+c.z)/3};}damaged=mixv(damaged,temporal,clampf(blend*os));}
  if(op==5){float permutation=setting0(v,op);damaged=permutation<1.5f?V3{damaged.y,damaged.z,damaged.x}:V3{damaged.z,damaged.x,damaged.y};}if(op==6)damaged={setting0(v,op),setting0(v,op),setting0(v,op)};if(op==7){float q=noise(cell.x+uv.x*setting0(v,op),cell.y+uv.y*setting0(v,op));damaged=mixv(damaged,{q,q,q},clampf(os));}if(pv(v,ParameterId::Split)>0&&op<0){float rgb=pv(v,ParameterId::Split)/fineGrid.x;damaged={sample(r.source,{p.x+rgb,p.y}).x,sample(r.source,p).y,sample(r.source,{p.x-rgb,p.y}).z};}float crush=pv(v,ParameterId::Crush),levels=mixf(256,3,crush);damaged={floorf(damaged.x*(levels-1)+.5f)/(levels-1),floorf(damaged.y*(levels-1)+.5f)/(levels-1),floorf(damaged.z*(levels-1)+.5f)/(levels-1)};float darken=1-crush*n*.6f;damaged={damaged.x*darken,damaged.y*darken,damaged.z*darken};color=mixv(fresh,damaged,pv(v,ParameterId::Amount)*strength);}
 out[0]=color.x;out[1]=color.y;out[2]=color.z;out[3]=channel(r.source,x,y,3);
}
}
#undef GR_HD