#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <new>
#include <mutex>
#include <string>
#include "ofxImageEffect.h"
#include "ofxParam.h"
#include "grid_rot/core.hpp"
#include "companion_exchange.hpp"
using namespace grid_rot;
static OfxHost*host=nullptr;static const OfxImageEffectSuiteV1*fx=nullptr;static const OfxPropertySuiteV1*prop=nullptr;static const OfxParameterSuiteV1*param=nullptr;static constexpr size_t N=static_cast<size_t>(ParameterId::Count);
struct Instance{OfxImageEffectHandle effect;OfxImageClipHandle source,output;OfxParamSetHandle set;std::array<OfxParamHandle,N>values{};OfxParamHandle preset,mode,bypass,useCuda,editCompanion,status;bool applying=false;std::mutex previewMutex;std::vector<unsigned char>preview;double previewFrame=-1e30;};
static void check(OfxStatus s){if(s!=kOfxStatOK)throw s;}static void text(OfxPropertySetHandle p,const char*n,const char*v,int i=0){check(prop->propSetString(p,n,i,v));}static void integer(OfxPropertySetHandle p,const char*n,int v,int i=0){check(prop->propSetInt(p,n,i,v));}static void real(OfxPropertySetHandle p,const char*n,double v,int i=0){check(prop->propSetDouble(p,n,i,v));}static OfxPropertySetHandle define(OfxParamSetHandle s,const char*t,const char*i,const char*l){OfxPropertySetHandle p;check(param->paramDefine(s,t,i,&p));text(p,kOfxPropLabel,l);return p;}static Instance*instance(OfxImageEffectHandle e){OfxPropertySetHandle p;void*v=nullptr;check(fx->getPropertySet(e,&p));check(prop->propGetPointer(p,kOfxPropInstanceData,0,&v));if(!v)throw kOfxStatErrBadHandle;return static_cast<Instance*>(v);}
static OfxStatus describe(OfxImageEffectHandle e){OfxPropertySetHandle p;check(fx->getPropertySet(e,&p));text(p,kOfxPropLabel,"GRID ROT");text(p,kOfxImageEffectPluginPropGrouping,"SIGNAL CULT");text(p,kOfxImageEffectPropSupportedContexts,kOfxImageEffectContextFilter,0);text(p,kOfxImageEffectPropSupportedContexts,kOfxImageEffectContextGeneral,1);text(p,kOfxImageEffectPropSupportedPixelDepths,kOfxBitDepthFloat);text(p,kOfxImageEffectPluginRenderThreadSafety,kOfxImageEffectRenderInstanceSafe);integer(p,kOfxImageEffectPropSupportsTiles,0);integer(p,kOfxImageEffectPropSupportsMultiResolution,0);integer(p,kOfxImageEffectPropTemporalClipAccess,1);integer(p,kOfxImageEffectPluginPropHostFrameThreading,0);return kOfxStatOK;}
static void range(OfxPropertySetHandle p,const ParameterDescriptor&d){if(d.kind==ParameterKind::Boolean){integer(p,kOfxParamPropDefault,int(d.initial));return;}if(d.kind==ParameterKind::Double){real(p,kOfxParamPropDefault,d.initial);real(p,kOfxParamPropMin,d.minimum);real(p,kOfxParamPropMax,d.maximum);real(p,kOfxParamPropDisplayMin,d.minimum);real(p,kOfxParamPropDisplayMax,d.maximum);real(p,kOfxParamPropIncrement,d.step);integer(p,kOfxParamPropDigits,3);return;}integer(p,kOfxParamPropDefault,int(d.initial));integer(p,kOfxParamPropMin,int(d.minimum));integer(p,kOfxParamPropMax,int(d.maximum));integer(p,kOfxParamPropDisplayMin,int(d.minimum));integer(p,kOfxParamPropDisplayMax,int(d.maximum));}
static const char*type(const ParameterDescriptor&d){if(d.kind==ParameterKind::Double)return kOfxParamTypeDouble;if(d.kind==ParameterKind::Boolean)return kOfxParamTypeBoolean;return kOfxParamTypeInteger;}
static OfxStatus context(OfxImageEffectHandle e){OfxPropertySetHandle p;for(const char*n:{"Source","Output"}){check(fx->clipDefine(e,n,&p));text(p,kOfxImageEffectPropSupportedComponents,kOfxImageComponentRGBA);integer(p,kOfxImageEffectPropSupportsTiles,0);}OfxParamSetHandle s;check(fx->getParamSet(e,&s));p=define(s,kOfxParamTypeChoice,"preset","Factory Preset");text(p,kOfxParamPropChoiceOption,"Custom",0);for(size_t i=0;i<kFactoryPresets.size();++i)text(p,kOfxParamPropChoiceOption,kFactoryPresets[i].name,int(i+1));integer(p,kOfxParamPropDefault,1);integer(p,kOfxParamPropAnimates,0);p=define(s,kOfxParamTypeChoice,"mode","Route");for(auto option:{"Step right","Step left","Random","LFO · sine","Random drops"})text(p,kOfxParamPropChoiceOption,option);integer(p,kOfxParamPropDefault,4);p=define(s,kOfxParamTypeBoolean,"bypass","Bypass");integer(p,kOfxParamPropDefault,0);p=define(s,kOfxParamTypeBoolean,"useCuda","Use CUDA when available");integer(p,kOfxParamPropDefault,1);integer(p,kOfxParamPropAnimates,0);p=define(s,kOfxParamTypePushButton,"editCompanion","Open GRID ROT Companion");text(p,kOfxParamPropHint,"Edit advanced packages in the GRID ROT Companion. Apply commits the complete look; Cancel leaves this instance unchanged.");p=define(s,kOfxParamTypeString,"companionStatus","Companion Status");text(p,kOfxParamPropDefault,"Ready");integer(p,kOfxParamPropEnabled,0);integer(p,kOfxParamPropAnimates,0);integer(p,kOfxParamPropPersistant,0);
 auto core=define(s,kOfxParamTypeGroup,"core","Core Controls");integer(core,kOfxParamPropGroupOpen,1);auto post=define(s,kOfxParamTypeGroup,"post","Post Damage");integer(post,kOfxParamPropGroupOpen,1);for(const auto&d:kParameterDescriptors){auto v=define(s,type(d),d.id,d.label);range(v,d);if(d.surface==ParameterSurface::Companion){integer(v,kOfxParamPropSecret,1);integer(v,kOfxParamPropAnimates,0);}else{text(v,kOfxParamPropParent,!std::strcmp(d.id,"shift")||!std::strcmp(d.id,"split")||!std::strcmp(d.id,"crush")?"post":"core");}}
 auto page=define(s,kOfxParamTypePage,"controlsPage","Controls");int index=0;for(const char*id:{"editCompanion","companionStatus","preset","mode","bypass","useCuda"})text(page,kOfxParamPropPageChild,id,index++);for(const auto&d:kParameterDescriptors)if(d.surface==ParameterSurface::Direct)text(page,kOfxParamPropPageChild,d.id,index++);return kOfxStatOK;}
static OfxStatus create(OfxImageEffectHandle e){auto d=new Instance{};try{d->effect=e;check(fx->clipGetHandle(e,"Source",&d->source,nullptr));check(fx->clipGetHandle(e,"Output",&d->output,nullptr));check(fx->getParamSet(e,&d->set));for(size_t i=0;i<N;++i)check(param->paramGetHandle(d->set,kParameterDescriptors[i].id,&d->values[i],nullptr));for(auto item:{std::pair{"preset",&d->preset},std::pair{"mode",&d->mode},std::pair{"bypass",&d->bypass},std::pair{"useCuda",&d->useCuda},std::pair{"editCompanion",&d->editCompanion},std::pair{"companionStatus",&d->status}})check(param->paramGetHandle(d->set,item.first,item.second,nullptr));OfxPropertySetHandle p;check(fx->getPropertySet(e,&p));check(prop->propSetPointer(p,kOfxPropInstanceData,0,d));return kOfxStatOK;}catch(...){delete d;throw;}}
static void setValue(OfxParamHandle h,const ParameterDescriptor&d,double value){if(d.kind==ParameterKind::Double)param->paramSetValue(h,value);else param->paramSetValue(h,int(std::round(value)));}
static ParameterValues values(Instance&,double);
static void editAdvanced(Instance&d,double time){try{grid_rot::ofx::CompanionState state;state.name="Resolve Instance";state.values=values(d,time);param->paramGetValueAtTime(d.mode,time,&state.mode);std::vector<unsigned char>preview;{std::lock_guard<std::mutex>lock(d.previewMutex);preview=d.preview;}auto result=grid_rot::ofx::editInCompanion(state,preview);if(result.applied){d.applying=true;param->paramEditBegin(d.set,"Apply GRID ROT Companion look");param->paramSetValue(d.mode,result.state.mode);for(size_t i=0;i<N;++i)setValue(d.values[i],kParameterDescriptors[i],result.state.values[i]);param->paramSetValue(d.preset,0);param->paramEditEnd(d.set);d.applying=false;}param->paramSetValue(d.status,result.message.c_str());}catch(const std::exception&error){d.applying=false;param->paramSetValue(d.status,error.what());}catch(...){d.applying=false;param->paramSetValue(d.status,"Companion session failed");}}
static OfxStatus changed(OfxImageEffectHandle e,OfxPropertySetHandle in){auto d=instance(e);char*n=nullptr,*reason=nullptr;prop->propGetString(in,kOfxPropName,0,&n);prop->propGetString(in,kOfxPropChangeReason,0,&reason);if(!n||!reason||std::strcmp(reason,kOfxChangeUserEdited)||d->applying)return kOfxStatReplyDefault;if(!std::strcmp(n,"editCompanion")){double time=0;prop->propGetDouble(in,kOfxPropTime,0,&time);editAdvanced(*d,time);return kOfxStatOK;}if(!std::strcmp(n,"preset")){int index=0;param->paramGetValue(d->preset,&index);if(index<1||index>int(kFactoryPresets.size()))return kOfxStatOK;const auto&p=kFactoryPresets[index-1];d->applying=true;param->paramEditBegin(d->set,"Apply GRID ROT preset");param->paramSetValue(d->mode,p.mode);for(size_t i=0;i<N;++i)setValue(d->values[i],kParameterDescriptors[i],p.values[i]);param->paramEditEnd(d->set);d->applying=false;return kOfxStatOK;}param->paramSetValue(d->preset,0);return kOfxStatReplyDefault;}
struct ScopedImage{OfxPropertySetHandle handle=nullptr;~ScopedImage(){if(handle)fx->clipReleaseImage(handle);}};static ConstImageView readImage(OfxPropertySetHandle h){void*p=nullptr;int bounds[4],rowBytes=0;char*depth=nullptr,*components=nullptr;check(prop->propGetPointer(h,kOfxImagePropData,0,&p));check(prop->propGetIntN(h,kOfxImagePropBounds,4,bounds));check(prop->propGetInt(h,kOfxImagePropRowBytes,0,&rowBytes));check(prop->propGetString(h,kOfxImageEffectPropPixelDepth,0,&depth));check(prop->propGetString(h,kOfxImageEffectPropComponents,0,&components));if(!p||std::strcmp(depth,kOfxBitDepthFloat)||std::strcmp(components,kOfxImageComponentRGBA))throw kOfxStatErrFormat;return{static_cast<float*>(p),bounds[2]-bounds[0],bounds[3]-bounds[1],4,rowBytes};}
static ParameterValues values(Instance&d,double time){ParameterValues result{};for(size_t i=0;i<N;++i){const auto&desc=kParameterDescriptors[i];if(desc.kind==ParameterKind::Double){double value=0;check(param->paramGetValueAtTime(d.values[i],time,&value));result[i]=std::clamp(value,double(desc.minimum),double(desc.maximum));}else{int value=0;check(param->paramGetValueAtTime(d.values[i],time,&value));result[i]=std::clamp(value,int(desc.minimum),int(desc.maximum));}}return result;}
static void copy(const ConstImageView&s,ImageView d){for(int y=0;y<d.height;++y){auto*dst=reinterpret_cast<float*>(reinterpret_cast<unsigned char*>(d.data)+std::ptrdiff_t(y)*d.row_bytes);auto*src=reinterpret_cast<const float*>(reinterpret_cast<const unsigned char*>(s.data)+std::ptrdiff_t(y)*s.row_bytes);std::copy(src,src+d.width*4,dst);}}
static double firstFrame(OfxImageClipHandle clip){OfxPropertySetHandle p;double range[2]{-1e9,1e9};if(fx->clipGetPropertySet(clip,&p)==kOfxStatOK)prop->propGetDoubleN(p,kOfxImageEffectPropFrameRange,2,range);return range[0];}
static OfxStatus render(OfxImageEffectHandle e,OfxPropertySetHandle in){auto d=instance(e);double time=0;check(prop->propGetDouble(in,kOfxPropTime,0,&time));ScopedImage src,dst;check(fx->clipGetImage(d->source,time,nullptr,&src.handle));check(fx->clipGetImage(d->output,time,nullptr,&dst.handle));RenderRequest request;request.source=readImage(src.handle);request.history[0]=request.source;request.values=values(*d,time);{std::unique_lock<std::mutex>lock(d->previewMutex,std::try_to_lock);if(lock.owns_lock()&&(d->preview.empty()||std::abs(time-d->previewFrame)>=12)){d->preview=grid_rot::ofx::makePreviewBmp(request.source);d->previewFrame=time;}}request.frame_number=time;int mode=4,bypass=0,useCuda=1;param->paramGetValueAtTime(d->mode,time,&mode);param->paramGetValueAtTime(d->bypass,time,&bypass);param->paramGetValue(d->useCuda,&useCuda);request.mode=mode;auto target=readImage(dst.handle);request.output={const_cast<float*>(target.data),target.width,target.height,target.row_bytes};if(bypass){copy(request.source,request.output);return kOfxStatOK;}OfxPropertySetHandle clipProperties;double fps=24;if(fx->clipGetPropertySet(d->source,&clipProperties)==kOfxStatOK)prop->propGetDouble(clipProperties,kOfxImageEffectPropFrameRate,0,&fps);request.time_seconds=time/(fps>0?fps:24);int lag=requiredPastFrames(request.values);std::array<ScopedImage,kMaxHistory-1>past;request.history_count=lag+1;double first=firstFrame(d->source);for(int i=1;i<=lag;++i){double wanted=std::max(first,time-i);if(fx->clipGetImage(d->source,wanted,nullptr,&past[i-1].handle)==kOfxStatOK&&past[i-1].handle)request.history[i]=readImage(past[i-1].handle);else request.history[i]=request.history[i-1];}auto status=useCuda&&cudaAvailable()?renderCuda(request):renderCpu(request);return status==RenderStatus::Ok?kOfxStatOK:kOfxStatFailed;}
static OfxStatus framesNeeded(OfxImageEffectHandle e,OfxPropertySetHandle in,OfxPropertySetHandle out){auto d=instance(e);double time=0;check(prop->propGetDouble(in,kOfxPropTime,0,&time));auto v=values(*d,time);double range[]={std::max(firstFrame(d->source),time-requiredPastFrames(v)),time};check(prop->propSetDoubleN(out,"OfxImageClipPropFrameRange_Source",2,range));return kOfxStatOK;}
static OfxStatus entry(const char*action,const void*handle,OfxPropertySetHandle in,OfxPropertySetHandle out){try{auto effect=(OfxImageEffectHandle)handle;if(!std::strcmp(action,kOfxActionLoad)){fx=(const OfxImageEffectSuiteV1*)host->fetchSuite(host->host,kOfxImageEffectSuite,1);prop=(const OfxPropertySuiteV1*)host->fetchSuite(host->host,kOfxPropertySuite,1);param=(const OfxParameterSuiteV1*)host->fetchSuite(host->host,kOfxParameterSuite,1);return fx&&prop&&param?kOfxStatOK:kOfxStatErrMissingHostFeature;}if(!std::strcmp(action,kOfxActionUnload))return kOfxStatOK;if(!std::strcmp(action,kOfxActionDescribe))return describe(effect);if(!std::strcmp(action,kOfxImageEffectActionDescribeInContext))return context(effect);if(!std::strcmp(action,kOfxActionCreateInstance))return create(effect);if(!std::strcmp(action,kOfxActionDestroyInstance)){delete instance(effect);return kOfxStatOK;}if(!std::strcmp(action,kOfxActionInstanceChanged))return changed(effect,in);if(!std::strcmp(action,kOfxImageEffectActionRender))return render(effect,in);if(!std::strcmp(action,kOfxImageEffectActionGetFramesNeeded))return framesNeeded(effect,in,out);if(!std::strcmp(action,kOfxImageEffectActionGetClipPreferences)){text(out,"OfxImageClipPropComponents_Output",kOfxImageComponentRGBA);text(out,"OfxImageClipPropDepth_Output",kOfxBitDepthFloat);integer(out,kOfxImageEffectFrameVarying,1);return kOfxStatOK;}return kOfxStatReplyDefault;}catch(OfxStatus s){return s;}catch(const std::bad_alloc&){return kOfxStatErrMemory;}catch(...){return kOfxStatFailed;}}
static void setHost(OfxHost*h){host=h;}static OfxPlugin plugin={kOfxImageEffectPluginApi,1,"com.signalcult.gridrot",1,0,setHost,entry};extern "C"{OfxExport int OfxGetNumberOfPlugins(){return 1;}OfxExport OfxPlugin*OfxGetPlugin(int i){return i==0?&plugin:nullptr;}}